name: DiT
channels:
  - pytorch
dependencies:
  - python >= 3.8
  - pytorch >= 1.13
  - torchvision
  - pip:
    - timm
    - diffusers
    - accelerate
    - protobuf
    - decorator
    - scipy
    - attrs
